# Form implementation generated from reading ui file 'numberOfPlayerDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogNumbers(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(287, 136)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.numberOfPlayer = QtWidgets.QSpinBox(Dialog)
        self.numberOfPlayer.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberOfPlayer.setFont(font)
        self.numberOfPlayer.setMinimum(1)
        self.numberOfPlayer.setMaximum(4)
        self.numberOfPlayer.setProperty("value", 1)
        self.numberOfPlayer.setObjectName("numberOfPlayer")
        self.verticalLayout.addWidget(self.numberOfPlayer)
        self.numberDialogOk = QtWidgets.QDialogButtonBox(Dialog)
        self.numberDialogOk.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.numberDialogOk.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.numberDialogOk.setObjectName("numberDialogOk")
        self.verticalLayout.addWidget(self.numberDialogOk)

        self.retranslateUi(Dialog)
        self.numberDialogOk.accepted.connect(Dialog.accept) # type: ignore
        self.numberDialogOk.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Number of player"))
